// ============================================================
// siteData.ts — AUTO-GENERATED by site_generator.py
// Do not edit manually. Re-run the generator to update.
// ============================================================

export type Variant = 'A' | 'B' | 'C' | 'D'

export interface ServiceItem {
  iconName: string
  name: string
  description: string
}

export interface ReviewItem {
  name: string
  rating: number
  text: string
  date: string
}

export interface WhyUsPoint {
  heading: string
  body: string
}

export interface ProcessStep {
  heading: string
  body: string
}

export interface FAQItem {
  question: string
  answer: string
}

export interface SiteData {
  businessName: string
  trade: string
  tagline: string
  phone: string
  email: string
  address: string
  city: string
  serviceArea: string
  googleBusinessUrl: string
  yearsExperience: number
  bookingUrl?: string
  variant: Variant
  hero: {
    heading: string
    subheading: string
    primaryCta: string
    secondaryCta: string
  }
  services: ServiceItem[]
  trustItems: string[]
  whyUs: {
    heading: string
    subheading: string
    points: WhyUsPoint[]
  }
  process: ProcessStep[]
  faqs: FAQItem[]
  reviews: ReviewItem[]
  seo: {
    title: string
    description: string
    canonicalUrl: string
  }
}

const siteData: SiteData = {
  businessName: 'Tradeworx Solutions Ltd',
  trade: 'Roofers',
  tagline: 'Birmingham\'s Trusted Roofing Experts Since 2014',
  phone: '+44 7347 229518',
  email: 'info@tradeworxsolutionsltd.co.uk',
  address: 'Grosvenor House, 11 St Paul\'s Square, Birmingham B3 1RB, United Kingdom',
  city: 'Birmingham',
  serviceArea: 'Birmingham',
  googleBusinessUrl: 'https://maps.google.com',
  yearsExperience: 24,

  variant: 'D',

  hero: {
    heading: 'Professional Roofers Serving Birmingham and Surrounding Areas',
    subheading: 'Tradeworx Solutions Ltd provides reliable roofing services across Birmingham with over 10 years of experience. Our skilled team delivers quality workmanship with a 4.8-star rating from 45+ satisfied customers.',
    primaryCta: 'Get a Free Quote',
    secondaryCta: 'Call Now',
  },

  services: [
    {
      iconName: 'Roof',
      name: 'Roof Repairs',
      description: 'We fix leaks, damaged tiles, and structural issues quickly and efficiently. Our repairs come with a guarantee for your peace of mind.',
    },
    {
      iconName: 'Home',
      name: 'New Roof Installation',
      description: 'Complete roof replacement using quality materials and modern techniques. We handle everything from planning to final inspection.',
    },
    {
      iconName: 'Shield',
      name: 'Roof Maintenance',
      description: 'Regular inspections and preventive maintenance to extend your roof\'s lifespan. We spot potential problems before they become costly repairs.',
    },
    {
      iconName: 'Droplets',
      name: 'Guttering Services',
      description: 'Installation, repair, and cleaning of gutters and downpipes. We ensure proper drainage to protect your property from water damage.',
    },
    {
      iconName: 'Search',
      name: 'Roof Inspections',
      description: 'Thorough assessments of your roof\'s condition with detailed reports. Perfect for insurance claims or before buying a property.',
    },
    {
      iconName: 'RefreshCw',
      name: 'Emergency Repairs',
      description: '24/7 emergency callout service for urgent roofing problems. We provide temporary solutions and permanent fixes to protect your home.',
    },
  ],

  trustItems: [
    '10+ Years Experience',
    'Fully Insured',
    'Free Quotes',
    'Local to Birmingham'
  ],

  whyUs: {
    heading: 'Why Choose Tradeworx Solutions Ltd?',
    subheading: 'With 10 years of experience and a 4.8-star rating, we\'re Birmingham\'s most trusted roofing specialists.',
    points: [
      {
        heading: 'Local Experts',
        body: 'Based in Birmingham, we know the local area and building requirements. Our team responds quickly and understands regional weather challenges.',
      },
      {
        heading: 'Quality Guaranteed',
        body: 'All our work comes with comprehensive warranties and insurance coverage. We use only approved materials and follow industry best practices.',
      },
      {
        heading: 'Transparent Pricing',
        body: 'No hidden costs or surprise charges on our detailed quotes. We provide clear pricing and stick to our estimates throughout the project.',
      },
      {
        heading: 'Excellent Reviews',
        body: 'Our 4.8-star Google rating reflects our commitment to customer satisfaction. We\'re proud of our reputation built on quality work and reliable service.',
      },
    ],
  },

  process: [
    {
      heading: 'Contact Our Team',
      body: 'Call us or fill out our online form for a free, no-obligation quote. We\'ll arrange a convenient time to visit your property.',
    },
    {
      heading: 'Property Assessment',
      body: 'Our experienced roofers inspect your roof and identify any issues. We provide a detailed written quote with transparent pricing.',
    },
    {
      heading: 'Schedule the Work',
      body: 'Once you approve the quote, we arrange a suitable start date. We coordinate all materials delivery and obtain necessary permits.',
    },
    {
      heading: 'Complete the Job',
      body: 'Our skilled team carries out the work to the highest standards with minimal disruption. We clean up thoroughly and provide warranty documentation.',
    },
  ],

  faqs: [
    {
      question: 'How long does a typical roof repair take?',
      answer: 'Most minor repairs are completed within a day, whilst major repairs or replacements can take 3-5 days depending on the size and complexity. We\'ll provide a clear timeline with your quote.',
    },
    {
      question: 'Do you provide free quotes?',
      answer: 'Yes, we offer free, no-obligation quotes for all roofing work. Our assessments include a thorough inspection and detailed written estimate with no hidden costs.',
    },
    {
      question: 'Are you fully insured?',
      answer: 'Absolutely. We carry full public liability insurance and all necessary trade certifications. You\'ll receive copies of our insurance documents before work begins.',
    },
    {
      question: 'What areas do you cover?',
      answer: 'We serve Birmingham and surrounding areas within a 20-mile radius. Contact us to confirm we cover your specific location for your roofing project.',
    },
    {
      question: 'Do you offer emergency callouts?',
      answer: 'Yes, we provide 24/7 emergency roofing services for urgent issues like storm damage or serious leaks. Emergency callouts incur additional charges but we\'ll make your property safe first.',
    },
    {
      question: 'What warranty do you provide?',
      answer: 'We offer comprehensive warranties on all our work, typically 5-10 years depending on the type of work completed. Materials come with manufacturer warranties which we\'ll transfer to you.',
    },
  ],

  reviews: [
    {
      name: 'Sarah M',
      rating: 5,
      text: 'Excellent service from Tradeworx Solutions. They fixed our leaking roof quickly and the price was very reasonable. The team was professional and cleaned up perfectly after the job.',
      date: 'November 2024',
    },
    {
      name: 'Mark T',
      rating: 5,
      text: 'Had our entire roof replaced and couldn\'t be happier with the quality of work. Great communication throughout and finished exactly when promised. Highly recommend for any roofing work.',
      date: 'October 2024',
    },
    {
      name: 'Jennifer L',
      rating: 5,
      text: 'Called them for an emergency repair after the storm and they came out the same day. Professional team who sorted the problem properly and fairly priced. Will definitely use again.',
      date: 'September 2024',
    },
  ],

  seo: {
    title: 'Tradeworx Solutions Ltd | Roofers in Birmingham',
    description: 'Professional roofers in Birmingham. 10+ years experience, 4.8-star rating, fully insured. Roof repairs, installations & maintenance. Call +44 7347 229518',
    canonicalUrl: 'https://preview-tradeworx-solutions-ltd.vercel.app',
  },
}

export default siteData

// CSS custom properties injected by site_generator.py
// These override :root variables in index.css at runtime
export const siteTheme = {
  '--color-primary':  '#1B2D45',
  '--color-accent':   '#E85D26',
  '--color-bg':       '#FAFAF8',
  '--color-text':     '#1A1A1A',
  '--color-muted':    '#6B7280',
  '--color-border':   '#E5E5E5',
  '--font-heading':   "'Instrument Serif', Georgia, serif",
  '--font-body':      "'DM Sans', system-ui, sans-serif",
}
